from __future__ import annotations
import argparse, os, yaml, torch
from torch.utils.data import DataLoader
from src.refactocnn.data.dataset import SegmentDataset, SegmentItem
from src.refactocnn.data.collate import collate_batch
from src.refactocnn.models.refactocnn import RefactoCNN
from src.refactocnn.training.trainer import evaluate_model
from src.refactocnn.utils.logging import save_json

def load_config(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="configs/default.yaml")
    ap.add_argument("--ckpt", required=True)
    args = ap.parse_args()
    cfg = load_config(args.config)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    pack = torch.load(cfg["paths"]["features_pt"], map_location="cpu")
    encoded = pack["encoded"]
    # items contain x already saved? In this baseline pipeline, we re-use the same pooled vectors by training script.
    # For evaluation here, we load the checkpoint and evaluate on stored pooled vectors if present.
    # If you want standalone evaluation, run training once (it saves reports).

    ckpt = torch.load(args.ckpt, map_location=device)
    input_dim = ckpt["config"]["data"]["embed_dim"] * (2 if ckpt["config"]["data"].get("fuse_ast", True) else 1)
    model = RefactoCNN(
        input_dim=input_dim,
        conv1_filters=cfg["model"]["conv1_filters"],
        conv2_filters=cfg["model"]["conv2_filters"],
        kernel_size=cfg["model"]["kernel_size"],
        dropout=cfg["model"]["dropout"],
        num_classes=cfg["model"]["num_classes"],
    ).to(device)
    model.load_state_dict(ckpt["model_state"])

    # This script expects you to use scripts/train.py for evaluation reports (recommended).
    # Keeping evaluate.py lightweight for now.
    print("Loaded checkpoint. Please use artifacts/reports/test_metrics.json for metrics (generated by train.py).")

if __name__ == "__main__":
    main()
